DROP TABLE IF EXISTS market;
CREATE TABLE market
(
    id     SERIAL NOT NULL PRIMARY KEY,
    name   VARCHAR(255),
    change DOUBLE PRECISION,
    sell   DOUBLE PRECISION,
    buy    DOUBLE PRECISION
);
